In [2]:
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq

In [6]:
df = pd.read_excel(r"C:\Users\zhang.yuan\Desktop\Painel da Agroindústria\Produtos Exportados.xlsx", skiprows=1)
df.to_csv('Produtos_Exportados.csv',  sep=';', index=False, encoding='utf-8')

In [6]:
df = pd.read_csv(r'Produtos_Exportados.csv')
df

,SETOR,SUBSETOR,PRODUTO,NCM,DESC_NCM,IND_MAPA,IND_OMC,DESC_ISIC_SECAO,IND_PRODUTO_AGRO_ONI
0,ANIMAIS VIVOS (EXCETO PESCADOS),ABELHAS VIVAS,ABELHAS VIVAS,1064100,ABELHAS,1,1,Agropecuária,1
1,ANIMAIS VIVOS (EXCETO PESCADOS),AVES DE RAPINA VIVAS,AVES DE RAPINA VIVAS,1063100,"AVES DE RAPINA,VIVAS",1,1,Agropecuária,1
2,ANIMAIS VIVOS (EXCETO PESCADOS),AVESTRUZES VIVAS,AVESTRUZES VIVAS,1060010,AVESTRUZES 'STRUTHIO CAMELUS' PARA REPRODUCAO,1,1,Agropecuária,1
3,ANIMAIS VIVOS (EXCETO PESCADOS),AVESTRUZES VIVAS,AVESTRUZES VIVAS,1063310,"AVESTRUZES (STRUTHIO CAMELUS), PARA REPRODUCAO",1,1,Agropecuária,1
4,ANIMAIS VIVOS (EXCETO PESCADOS),AVESTRUZES VIVAS,AVESTRUZES VIVAS,1063390,OUTROS AVESTRUZES,1,1,Agropecuária,1
...,...,...,...,...,...,...,...,...,...
3068,SUCOS,SUCOS DE OUTRAS FRUTAS,SUCOS DE OUTROS CÍTRICOS,20093100,SUCO DE OUTS.CITRICOS COM VALOR BRIX<=20,1,1,Indústria de Transformação,0
3069,SUCOS,SUCOS DE OUTRAS FRUTAS,SUCOS DE OUTROS CÍTRICOS,20093900,OUTS.SUCOS DE OUTS.CITRICOS,1,1,Indústria de Transformação,0
3070,SUCOS,SUCOS DE OUTRAS FRUTAS,SUCOS DE UVA,20096000,"SUCOS DE UVAS (INCL.OS MOSTOS DE UVAS),NAO FER...",1,1,Indústria de Transformação,0
3071,SUCOS,SUCOS DE OUTRAS FRUTAS,SUCOS DE UVA,20096100,SUCO DE UVAS COM VALOR BRIX<=30,1,1,Indústria de Transformação,0
3072,SUCOS,SUCOS DE OUTRAS FRUTAS,SUCOS DE UVA,20096900,OUTROS SUCOS DE UVAS,1,1,Indústria de Transformação,0

In [5]:
df = pd.read_excel(r"C:\Users\zhang.yuan\Desktop\Painel da Agroindústria\Produtos Importados.xlsx", skiprows=1)
df.to_csv('Produtos_Importados.csv', index=False, sep=';', encoding='utf-8')

#df = pd.read_csv(r'Produtos_Importados.csv', sep=';')